[package]
name = "tai"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.9"
spin = "0.9.8"
volatile = "0.6.1"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]
